### ISSUE TITLE
Fix internal package dependencies.

### ISSUE THREAD

**Issue by neilogd** [Psybrus/Psybrus#106]
When adding a package cross ref, currently it will only cause the package to wait till another is loaded *except* the current package.

This should be changed to either reorder the loading sequence so that dependent resources load, and complete loading, first, or by imposing the restriction that resources may not be ready when first constructed + initialised.

**Comment by neilogd** [comment]
A 'postLoad' could also be implemented if required, since this would be a good point to markup resources.

**Comment by vk2gpu** [comment]
Dup of #118
