### ISSUE TITLE
CsResource: replace initialise with constructor.

### ISSUE THREAD

**Issue by neilogd** [Psybrus/Psybrus#34]
Relying on calls to initialise to be passed to base classes is unreliable and error prone. Replace all this with calls to a constructor and modify code appropriately by first calling initialise from a constructor, and deprecating later.

**Comment by vk2gpu** [comment]
initialise is now only an overload that is called after being added to the scene. Does work post-serialisation, so it's fine as it is now. The original initialise has been moved entirely to the constructor.
