### ISSUE TITLE
Group Engine and External libraries into subfolders in project view

### ISSUE THREAD

**Issue by Dezzles** [Psybrus/Psybrus#48]
Visual studio (at least Professional version) allows projects inside a solution to be grouped into folders.

It may be worth moving the Engine and External libraries into folders in order to have the project view much cleaner

**Comment by Dezzles** [comment]
![image](https://cloud.githubusercontent.com/assets/3052698/7693001/153c624a-fe0e-11e4-9517-bcce0dc04b12.png)

This is now supported and currently pushed to develop

https://github.com/Psybrus/Psybrus/commit/74499a057b5c085e611ad2d5b3adcbaef5805ef8

**Comment by neilogd** [comment]
Sweet as :)
