### ISSUE TITLE
Google Analytics integration

### ISSUE THREAD

**Issue by neilogd** [Psybrus/Psybrus#58]
We should look at integrating this at some point, very useful game jams and what not.

Would need an HTTP client library to be embedded, so we should investigate which one is best. Libcurl is probably the best option: http://curl.haxx.se/docs/copyright.html

**Comment by vk2gpu** [comment]
Treating as responsibility for the user to implement, as @Kimau has mention just need a good HTTP stack. Raknet I believe has this already.
