### ISSUE TITLE
shared_ptr, weak_ptr, unique_ptr support in reflection

### ISSUE THREAD

**Issue by neilogd** [Psybrus/Psybrus#68]
Want support for these, need to look at a way to template off dereferencing policies.

**Comment by neilogd** [comment]
unique_ptr could be the easiest as it *should* be a simple deref except in function pointer cases for custom deleters.

**Comment by vk2gpu** [comment]
No support for shared_ptr & weak_ptr. unique_ptr will be covered by #76
