### ISSUE TITLE
Clean up branches.

### ISSUE THREAD

**Issue by neilogd** [Psybrus/Psybrus#88]
I'm going to move to a model more like git-flow:

master - this is what as considered to be always working. I might look into having a set of tests that need to pass before anything makes it to here.

develop - this is what is currently in development. Must pass tests before going back to master.

features/<name> - If developing a feature, branch from develop, and merge back to develop when the feature is done. Branch can be kept around, or deleted. Your choice.

bugfixes/<name> - If fixing bugs, and they are likely to be a significant change (more than just a couple of files worth of changes), branch to here, and merge back to develop. Can branch from master or develop initially.

personal/<user>/<name> - Any personal branches can go here. Mostly for backing up purposes. We should be trying to work in feature branches branched from develop where possible.

@Dezzles, does this seem logical and make sense? It's mostly just for some uniformity in naming of branches.

**Comment by Dezzles** [comment]
This seems super reasonable to me. I think that merges from develop to
master should be planned instead of just when a piece of work is done. I.e.
milestone completions

**Comment by neilogd** [comment]
More planning for develop -> master seems good to me. We don't exactly have
milestones as such though. Could always just fabricate some and assign
bugs/tasks to em. If all bugs get completed for a milestone, then do the
merge to master?

I was thinking about having a staging between develop and master to do
testing, but that is a bit overkill unless there is automated testing to
verify everything.
