### ISSUE TITLE
D3D11 improvements.

### ISSUE THREAD

**Issue by neilogd** [Psybrus/Psybrus#89]
Currently it's a little rushed of an implementation, mostly just because the intent was to "get it done". Shortcuts have been taken, so it will need some improvements:

- Better view management.
- Better render state management.
- Break it up a little more than the cpp/h pair.

**Comment by vk2gpu** [comment]
Has been optimised a bit, but needs to be broken up a little maybe?

**Comment by vk2gpu** [comment]
No. Just remove D3D11 implementation. OpenGL[ES], D3D12, and later Vulkan should be only targets we care about.
