### ISSUE TITLE
Investigate using generalised attributes for reflection 

### ISSUE THREAD

**Issue by neilogd** [Psybrus/Psybrus#96]
Generalised attributes (http://en.cppreference.com/w/cpp/language/attributes) would be a bit cleaner to work with going forward, and allow the use of libclang to assist with code generation, instead of the manual process we currently have.

**Comment by neilogd** [comment]
Another advantage of this is that all reflection references can be trimmed down to minimum. Should only need to include a small subset of the reflection headers, or even separate out the reflection into a library independent of Psybrus.

**Comment by vk2gpu** [comment]
Not possible right now. Unsupported features in all required compilers. Reinvestigate later.
